clear;
clc;
close all;

%% =========================
% 参数
%% =========================
R = 100;              % 磁轴承安装半径

bearing_radius = 10;  % 磁轴承半径
bearing_length = 25;  % 磁轴承长度

floater_radius = 4;   % 浮子半径

platform_radius = 60; % 刚体半径
platform_thickness = 6;

%% =========================
% 创建图形
%% =========================

figure('Color','w');

hold on;
grid on;
axis equal;

xlabel('X');
ylabel('Y');
zlabel('Z');

view(35,25);

%% =========================
% 中央刚体
%% =========================

[XP,YP,ZP] = cylinder(platform_radius,80);

ZP = ZP*platform_thickness - platform_thickness/2;

surf(XP,YP,ZP,...
    'FaceColor',[0.85 0.85 0.85],...
    'EdgeColor','k',...
    'LineWidth',0.5);

plot3(0,0,0,...
    'ko',...
    'MarkerFaceColor','k',...
    'MarkerSize',8);

text(0,0,10,...
    'Rigid Body',...
    'FontSize',12,...
    'HorizontalAlignment','center');

%% =========================
% 三个磁轴承
%% =========================

angles = [0 120 240];

for k = 1:3

    %% ---------------------
    % 位置
    %% ---------------------

    th = deg2rad(angles(k));

    p = [ ...
        R*cos(th)
        R*sin(th)
        0 ];

    %% ---------------------
    % 局部坐标系
    %% ---------------------

    er = -p/norm(p);      % 指向原点

    ez = [0;0;1];

    et = cross(ez,er);
    et = et/norm(et);

    %% ---------------------
    % 磁轴承圆柱
    %% ---------------------

    [xc,yc,zc] = cylinder(bearing_radius,60);

    zc = (zc-0.5)*bearing_length;

    pts = [ ...
        xc(:)' ;
        yc(:)' ;
        zc(:)' ];

    % 本地:
    % x -> et
    % y -> ez
    % z -> er

    Rot = [et ez er];

    pts_global = Rot*pts;

    X = reshape(pts_global(1,:),size(xc)) + p(1);
    Y = reshape(pts_global(2,:),size(yc)) + p(2);
    Z = reshape(pts_global(3,:),size(zc)) + p(3);

    surf(X,Y,Z,...
        'FaceColor',[0.65 0.80 1.00],...
        'EdgeColor','k',...
        'LineWidth',0.5);

    %% ---------------------
    % 轴线
    %% ---------------------

    plot3([p(1) 0],...
          [p(2) 0],...
          [p(3) 0],...
          'k--',...
          'LineWidth',1);

    %% ---------------------
    % 浮子位置
    %% ---------------------

    pf = p + 18*er;

    thf = linspace(0,2*pi,60);

    fill3( ...
        pf(1)+floater_radius*cos(thf), ...
        pf(2)+floater_radius*sin(thf), ...
        pf(3)+zeros(size(thf)), ...
        [1 0.85 0], ...
        'EdgeColor','k',...
        'LineWidth',1);

    %% ---------------------
    % 连杆
    %% ---------------------

    plot3([0 pf(1)],...
          [0 pf(2)],...
          [0 pf(3)],...
          'k-',...
          'LineWidth',2);

    %% ---------------------
    % er (红色)
    %% ---------------------

    quiver3( ...
        p(1),p(2),p(3), ...
        20*er(1), ...
        20*er(2), ...
        20*er(3), ...
        'Color',[1 0 0], ...
        'LineWidth',2,...
        'MaxHeadSize',0.8);

    %% ---------------------
    % Ft (绿色)
    %% ---------------------

    quiver3( ...
        p(1),p(2),p(3), ...
        25*et(1), ...
        25*et(2), ...
        25*et(3), ...
        'Color',[0 0.7 0], ...
        'LineWidth',3,...
        'MaxHeadSize',0.8);

    %% ---------------------
    % Fz (蓝色)
    %% ---------------------

    quiver3( ...
        p(1),p(2),p(3), ...
        0,0,25, ...
        'Color',[0 0 1], ...
        'LineWidth',3,...
        'MaxHeadSize',0.8);

    %% ---------------------
    % 标注
    %% ---------------------

    text( ...
        p(1), ...
        p(2), ...
        p(3)+15, ...
        sprintf('MB%d',k), ...
        'FontSize',12);

    text( ...
        p(1)+28*et(1), ...
        p(2)+28*et(2), ...
        p(3), ...
        sprintf('Ft%d',k), ...
        'FontSize',11);

    text( ...
        p(1), ...
        p(2), ...
        28, ...
        sprintf('Fz%d',k), ...
        'FontSize',11);

end

%% =========================
% 全局坐标系
%% =========================

axis_len = 40;

% X轴（红）
quiver3(0,0,0,...
    axis_len,0,0,...
    'Color',[1 0 0],...
    'LineWidth',3,...
    'MaxHeadSize',0.5);

% Y轴（绿）
quiver3(0,0,0,...
    0,axis_len,0,...
    'Color',[0 0.7 0],...
    'LineWidth',3,...
    'MaxHeadSize',0.5);

% Z轴（蓝）
quiver3(0,0,0,...
    0,0,axis_len,...
    'Color',[0 0 1],...
    'LineWidth',3,...
    'MaxHeadSize',0.5);

text(axis_len+5,0,0,...
    'X',...
    'Color',[1 0 0],...
    'FontSize',12,...
    'FontWeight','bold');

text(0,axis_len+5,0,...
    'Y',...
    'Color',[0 0.7 0],...
    'FontSize',12,...
    'FontWeight','bold');

text(0,0,axis_len+5,...
    'Z',...
    'Color',[0 0 1],...
    'FontSize',12,...
    'FontWeight','bold');

title('Three Magnetic Bearings with Floaters and Rigid Body');