%% parameters
clear;
H = 0.035;
platform_radius = 0.1;
floater_hight = 0.03;

Rz = @(th) [cos(th), -sin(th), 0; sin(th), cos(th), 0; 0, 0, 1];
Ry = @(th) [cos(th), 0, sin(th); 0, 1, 0; -sin(th), 0, cos(th)];

cross_matrix = @(a) [0, -a(3), a(2); a(3), 0, -a(1); -a(2), a(1), 0];

%% frame-platform to frame-mb0
R0 = Ry(deg2rad(-90)) * Rz(deg2rad(-90));
t0 = [(floater_hight * 0.5 + platform_radius); 0; -H];

T_mb0_2_platform = [R0, t0; 0, 0, 0, 1];

%% frame-platform to frame-mb1
R1 = Rz(deg2rad(-60)) * Ry(deg2rad(90)) * Rz(deg2rad(90));
t1 = [(floater_hight * 0.5 + platform_radius) * cos(pi/3*2); ...
(floater_hight * 0.5 + platform_radius) * sin(pi/3*2); -H];

T_mb1_2_platform = [R1, t1; 0, 0, 0, 1];

%% frame-platform to frame-mb2

R2 = Rz(deg2rad(60)) * Ry(deg2rad(90)) * Rz(deg2rad(90));
t2 = [(floater_hight * 0.5 + platform_radius) * cos(pi/3*4); ...
(floater_hight * 0.5 + platform_radius) * sin(pi/3*4); -H];

T_mb2_2_platform = [R2, t2; 0, 0, 0, 1];

%% calculate the torque in frame platform generated by force_x in mb0

% force in mb0 frame
f_x_fp = T_mb0_2_platform * [1 0 0 1]' - T_mb0_2_platform * [0 0 0 1]';
f_x_fp = f_x_fp(1:3);

f_y_fp = T_mb0_2_platform * [0 1 0 1]' - T_mb0_2_platform * [0 0 0 1]';
f_y_fp = f_y_fp(1:3);

r_fp = T_mb0_2_platform * [0 0 0 1]';
r_fp = r_fp(1:3);

torque_x_fp = cross(r_fp, f_x_fp);
torque_y_fp = cross(r_fp, f_y_fp);

%% 3D plot of force, position, and torque vectors
figure;
hold on; axis equal; grid on;
xlabel('X'); ylabel('Y'); zlabel('Z');
title('Force, Position, and Torque Vectors in Platform Frame');

% position vector (from origin)
quiver3(0, 0, 0, r_fp(1), r_fp(2), r_fp(3), 'b', 'LineWidth', 2, 'DisplayName', 'r (position)');

% force x vector (at position point)
quiver3(r_fp(1), r_fp(2), r_fp(3), ...
        f_x_fp(1), f_x_fp(2), f_x_fp(3), 'r', 'LineWidth', 2, 'DisplayName', 'f_x (force x)');

% force y vector (at position point)
quiver3(r_fp(1), r_fp(2), r_fp(3), ...
        f_y_fp(1), f_y_fp(2), f_y_fp(3), 'm', 'LineWidth', 2, 'DisplayName', 'f_y (force y)');

% torque x vector (from origin)
quiver3(0, 0, 0, torque_x_fp(1), torque_x_fp(2), torque_x_fp(3), 'g', 'LineWidth', 2, 'DisplayName', '\tau_x (torque x)');

% torque y vector (from origin)
quiver3(0, 0, 0, torque_y_fp(1), torque_y_fp(2), torque_y_fp(3), 'c', 'LineWidth', 2, 'DisplayName', '\tau_y (torque y)');

legend('Location', 'best');
view(45, 30);

%% mb0_fx, mb0_fy -> fx, fy, fz, tx, ty, tz

r0_fp = T_mb0_2_platform * [0 0 0 1]';

F0 = R0(:, 1:2);

T0 = cross_matrix(r0_fp) * R0;
T0 = T0(:, 1:2);

FT0 = [F0; T0];

%% mb1_fx, mb1_fy -> fx, fy, fz, tx, ty, tz

r1_fp = T_mb1_2_platform * [0 0 0 1]';

F1 = R1(:, 1:2);

T1 = cross_matrix(r1_fp) * R1;
T1 = T1(:, 1:2);

FT1 = [F1; T1];

%% mb2_fx, mb1_fy -> fx, fy, fz, tx, ty, tz

r2_fp = T_mb2_2_platform * [0 0 0 1]';

F2 = R2(:, 1:2);

T2 = cross_matrix(r2_fp) * R2;
T2 = T2(:, 1:2);

FT2 = [F2; T2];

FT = [FT0 FT1 FT2];

%% 位置速度转换：px,py,pz,wx,wy,wz -> mb0_x, mb0_ys
%% 6自由度换算到每一个磁轴承也会是6个运动自由度，此时控制两个自由度位移没有意义
%% 理论上应该从platform的6个自由度运动算出6个力，再将6个力转换到各个磁轴承上
